In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("first.csv")
print(df)
# csv=>comma separated value

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [38]:
print(df.head()) # Display the first few rows of the DataFrame
print(df.tail()) # Display the last few rows of the DataFrame
print(df.shape) # Display the shape of the DataFrame (rows, columns)
print(df.columns) # Display the column names of the DataFrame
print(df.info()) # Display a concise summary of the DataFrame
print(df.describe()) # Display summary statistics of the DataFrame
# Note: Replace 'column_name' with the actual name of the column you want to analyze.

   Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2024                     Level 1                99999       All industries
1  2024                     Level 1                99999       All industries
2  2024                     Level 1                99999       All industries
3  2024                     Level 1                99999       All industries
4  2024                     Level 1                99999       All industries

                Units Variable_code  \
0  Dollars (millions)           H01
1  Dollars (millions)           H04
2  Dollars (millions)           H05
3  Dollars (millions)           H07
4  Dollars (millions)           H08

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance
1  Sales, government funding, grants and subsidies  Financial performance
2                Interest, dividends and donations  Financial performance
3                             Non-operating income  Financial performance
4                                Total expenditure  Financial performance

    Value                             Industry_code_ANZSIC06
0  979594  ANZSIC06 divisions A-S (excluding classes K633...
1  838626  ANZSIC06 divisions A-S (excluding classes K633...
2  112188  ANZSIC06 divisions A-S (excluding classes K633...
3   28781  ANZSIC06 divisions A-S (excluding classes K633...
4  856960  ANZSIC06 divisions A-S (excluding classes K633...
       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC       Units Variable_code  \
55615  Food product manufacturing  Percentage           H37
55616  Food product manufacturing  Percentage           H38
55617  Food product manufacturing  Percentage           H39
55618  Food product manufacturing  Percentage           H40
55619  Food product manufacturing  Percentage           H41

                             Variable_name Variable_category Value  \
55615                          Quick ratio  Financial ratios    52
55616  Margin on sales of goods for resale  Financial ratios    40
55617                     Return on equity  Financial ratios    12
55618               Return on total assets  Financial ratios     5
55619                Liabilities structure  Financial ratios    46

                                  Industry_code_ANZSIC06
55615  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619  ANZSIC06 groups C111, C112, C113, C114, C115, ...
(55620, 10)
Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55620 entries, 0 to 55619
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         55620 non-null  int64
 1   Industry_aggregation_NZSIOC  55620 non-null  object
 2   Industry_code_NZSIOC         55620 non-null  object
 3   Industry_name_NZSIOC         55620 non-null  object
 4   Units                        55620 non-null  object
 5   Variable_code                55620 non-null  object
 6   Variable_name                55620 non-null  object
 7   Variable_category            55620 non-null  object
 8   Value                        55620 non-null  object
 9   Industry_code_ANZSIC06       55620 non-null  object
dtypes: int64(1), object(9)
memory usage: 4.2+ MB
None
               Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000

In [15]:
import numpy as np
import pandas as pd
df2=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])
print(df2)
print(df2.head())
print(df.to_csv("first.csv"))
df.to_csv("first.csv",index=False) # Save DataFrame to CSV without index

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19
      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19
None

In [20]:
# accessing elements
# 1)row=> .loc[row_index]
# 2)coloumn=> .iloc[column_index]

print(df2.loc["row1"])
print(type(df2.loc["row1"]))

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int32
<class 'pandas.core.series.Series'>

In [32]:
# iloc[row_index, column_index]
print(type(df2.iloc[:2,2:]))
print(df2.iloc[:2,2:])
# convert dataframe into array
print(df2.iloc[2:,:2].values)
print(df2.iloc[2:,:2].values.shape)
print(df2["col1"].value_counts())
print(df2["col1"].unique())

<class 'pandas.core.frame.DataFrame'>
      col3  col4
row1     2     3
row2     6     7
[[ 8  9]
 [12 13]
 [16 17]]
(3, 2)
col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64
[ 0  4  8 12 16]

In [31]:
print(df2.isnull().sum())

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [37]:
print(df2["col1"])
df2[["col3","col4"]]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int32

      col3  col4
row1     2     3
row2     6     7
row3    10    11
row4    14    15
row5    18    19

In [16]:
import pandas as pd
# Reading a CSV file into a DataFrame
test_df=pd.read_csv("second.csv",sep=";")  # Specify the separator as semicolon
test_df2=pd.read_csv("second.csv",sep=",")  # Specify the separator as semicolon
print(test_df  )
print(test_df.head()  )
print(test_df2  )
print(test_df2.head()  )
print(test_df2['col1'].value_counts())  # Count occurrences of each value in the 'x0' column
test_df2['col1'].unique()  # Get unique values in the 'x0' column

  col1,col2,col3,col4
0             0,1,2,3
1             4,5,6,7
2           8,9,10,11
3         12,13,14,15
4         16,17,18,19
  col1,col2,col3,col4
0             0,1,2,3
1             4,5,6,7
2           8,9,10,11
3         12,13,14,15
4         16,17,18,19
   col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
   col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

array([ 0,  4,  8, 12, 16], dtype=int64)

In [18]:
print(test_df2.dropna(axis=0))
test_df2.corr()

   col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19

      col1  col2  col3  col4
col1   1.0   1.0   1.0   1.0
col2   1.0   1.0   1.0   1.0
col3   1.0   1.0   1.0   1.0
col4   1.0   1.0   1.0   1.0